### PR TITLE
fix: wrong field name that cause AC not shown

### LINKED ISSUE #1: AC and IR Device not shown as Devices
Hi, thank you for creating this awesome project.

I've a question (or maybe a bug report). Why my IR and AC is not shown as devices at homebridge menu or even at the Home app on iOS?

I've add the config like below:
Screen Shot 2021-06-16 at 05 42 32

Thank you

### PR DESCRIPTION
**Pull request by ridhoperdana**
fix #1

### CODE REVIEW

**Comment by prasad-edlabadka** [comment]
Don't know if there is API difference between US and EU. But I get device config as below
{
  active_time: 1619974447,
  biz_type: 0,
  category: **'infrared_ac',**
  create_time: 1619974447,
  icon: 'smart/icon/001453365846342fhj9e/11c62df7bd89c10f43d3e5ee8d13b4f4.png',

Also, there isn't remote_id field. It's just 'id'. Can you put the JSON you get as a response by putting following statement at at Line 79 in platform.ts?

this.log.debug(device);

**Comment by prasad-edlabadka** [comment]
Or may be its that /v1.0/infrareds/${deviceId}/remotes API call is successful in USA but not in the EU and data structure is different.

**Comment by ridhoperdana** [comment]
Hmm, if the response between region is different, it will need a different PR.

when I requesting this URI `https://openapi.tuyaus.com/v1.0/infrareds/{ir_id}/remotes` what I get is

```json
{
    "result": [
        {
            "area_id": "0",
            "brand_id": "2152",
            "brand_name": "Sanken",
            "category_id": "5",
            "iptv_type": 0,
            "operator_id": "0",
            "remote_id": "remote_id",
            "remote_index": "11272",
            "remote_name": "Ac Ridho",
            "t": 1623744730279
        }
    ],
    "success": true,
    "t": 1623936015537
}
```

reference:
https://developer.tuya.com/en/docs/cloud/universal-infrared?id=K9jgsgd7buln4#title-24-Air%20conditioner%20remote%20control

@prasad-edlabadka

**Comment by prasad-edlabadka** [comment]
@ridhoperdana Can you please try updating to 0.0.3? It should fix the issue.

**Comment by prasad-edlabadka** [comment]
No longer required. Fix already added in v0.0.6

**Comment by ridhoperdana** [comment]
I am sorry but when I update to the latest version, it is still not working. The list is shown but the command is not triggered. @prasad-edlabadka

**Comment by prasad-edlabadka** [comment]
Can you please send logs after trying to switch on the AC or turning it off?

**Pull request closed without merging**
